//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalAutomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physician
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Physician()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int PhysicianID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> SpecializationID { get; set; }
        public string Gender { get; set; }
        public Nullable<int> TotalExperience { get; set; }
        public string Education { get; set; }
        public string CurrentStatus { get; set; }
        public int UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual SpecializationData SpecializationData { get; set; }
        public virtual User User { get; set; }
    }
}
