//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalAutomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalespersonOrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalespersonOrderDetail()
        {
            this.DrugDeliveries = new HashSet<DrugDelivery>();
        }
    
        public int SalespersonOrderID { get; set; }
        public string DrugName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<int> SalespersonID { get; set; }
        public Nullable<int> SupplierID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugDelivery> DrugDeliveries { get; set; }
        public virtual Salesperson Salesperson { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
